/*
 *
 * MyStuff constants
 *
 */

export const DEFAULT_ACTION = 'app/MyStuff/DEFAULT_ACTION';

export const LOAD_PROJECTS = 'app/MyStuff/LOAD_PROJECTS';
export const LOAD_PROJECTS_FAILURE = 'app/MyStuff/LOAD_PROJECTS_FAILURE';
export const LOAD_PROJECTS_SUCCESS = 'app/MyStuff/LOAD_PROJECTS_SUCCESS';
export const LOAD_DELETED_SUCCESS = 'app/MyStuff/LOAD_DELETED_SUCCESS';
export const DELETE_PROJECT = 'app/MyStuff/DELETE_PROJECT';
export const DELETE_PROJECT_FAILURE = 'app/MyStuff/DELETE_PROJECT_FAILURE';
export const UNDELETE_PROJECT = 'app/MyStuff/UNDELETE_PROJECT';
export const UNDELETE_PROJECT_FAILURE = 'app/MyStuff/UNDELETE_PROJECT_FAILURE';
export const UPDATE_PROJECTS_SUCCESS = 'app/MyStuff/UPDATE_PROJECTS_SUCCESS';
export const UPDATE_DELETED_SUCCESS = 'app/MyStuff/UPDATE_DELETED_SUCCESS';
