/*
 *
 * ProjectPreview constants
 *
 */

export const DEFAULT_ACTION = 'app/ProjectPreview/DEFAULT_ACTION';

export const LOAD_PROJECT_DETAILS = 'app/ProjectPreview/LOAD_PROJECT_DETAILS';
export const LOAD_PROJECT_DETAILS_FAILURE =
  'app/ProjectPreview/LOAD_PROJECT_DETAILS_FAILURE';
export const LOAD_PROJECT_DETAILS_SUCCESS =
  'app/ProjectPreview/LOAD_PROJECT_DETAILS_SUCCESS';
export const LOAD_USER_INFO = 'app/ProjectPreview/LOAD_USER_INFO';
export const LOAD_USER_INFO_SUCCESS =
  'app/ProjectPreview/LOAD_USER_INFO_SUCCESS';
export const LOAD_USER_INFO_FAILURE =
  'app/ProjectPreview/LOAD_USER_INFO_FAILURE';
export const LOAD_PROJECT_COMMENTS = 'app/ProjectPreview/LOAD_PROJECT_COMMENTS';
export const LOAD_PROJECT_COMMENTS_SUCCESS =
  'app/ProjectPreview/LOAD_PROJECT_COMMENTS_SUCCESS';
export const LOAD_PROJECT_COMMENTS_FAILURE =
  'app/ProjectPreview/LOAD_PROJECT_COMMENTS_FAILURE';
export const ADD_PROJECT_COMMENT = 'app/ProjectPreview/ADD_PROJECT_COMMENT';
export const ADD_PROJECT_COMMENT_FAILURE =
  'app/ProjectPreview/ADD_PROJECT_COMMENT_FAILURE';
export const USER_TOGGLE_LIKE = 'app/ProjectPreview/USER_TOGGLE_LIKE';
export const USER_TOGGLE_LIKE_FAILURE =
  'app/ProjectPreview/USER_TOGGLE_LIKE_FAILURE';
export const USER_TOGGLE_LIKE_SUCCESS =
  'app/ProjectPreview/USER_TOGGLE_LIKE_SUCCESS';
export const USER_TOGGLE_BOOKMARK = 'app/ProjectPreview/USER_TOGGLE_BOOKMARK';
export const USER_TOGGLE_BOOKMARK_FAILURE =
  'app/ProjectPreview/USER_TOGGLE_BOOKMARK_FAILURE';
export const USER_TOGGLE_BOOKMARK_SUCCESS =
  'app/ProjectPreview/USER_TOGGLE_BOOKMARK_SUCCESS';
export const UPDATE_PROJECT_INFORMATION =
  'app/ProjectPreview/UPDATE_PROJECT_INFORMATION';
export const UPDATE_PROJECT_INFORMATION_FAILURE =
  'app/ProjectPreview/UPDATE_PROJECT_INFORMATION_FAILURE';
export const UPDATE_PROJECT_INFORMATION_SUCCESS =
  'app/ProjectPreview/UPDATE_PROJECT_INFORMATION_SUCCESS';
export const UPDATE_PROJECT_COMMENT_PERMISSIONS =
  'app/ProjectPreview/UPDATE_PROJECT_COMMENT_PERMISSIONS';
export const UPDATE_PROJECT_COMMENT_PERMISSIONS_FAILURE =
  'app/ProjectPreview/UPDATE_PROJECT_COMMENT_PERMISSIONS_FAILURE';
export const SET_SUCCESS = 'app/ProjectPreview/SET_SUCCESS';
